[package]
name = "wrapperc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
f3l_glam = "0.1"

[build-dependencies]
cbindgen = {version = "0.27"}
csbindgen = {version = "1.9"}