[package]
name = "wrapperc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
f3l = { version = "0.3", default-features = false, features = ["core"]}

[build-dependencies]
cbindgen = {version = "0.27"}
csbindgen = {version = "1.9"}